# specify python as the language
language: python

# python versions to be used for testing
python:
   - "3.5"

install:
   - pip install -r requirements.txt


# test script
script:
   - wget https://raw.githubusercontent.com/dosumis/dead_simple_owl_design_patterns/master/spec/DOSDP_schema_full.yaml
   - python src/test_patterns.py validated_patterns/
